- name: Update OS
  hosts: all
  become: true
  tasks:
    - name: Check OS
      ansible.builtin.apt:
        update_cache: true
    - name: Install build essentials and development tools
      ansible.builtin.apt:
        name:
          - build-essential
          - git
          - curl
          - wget
          - unzip
          - vim
          - nano
          - htop
          - tree
          - jq
          - python3
          - python3-pip
          - nodejs
          - npm
        state: present
        update_cache: true
